/*
* DRMDB_Init.sql
* 2020039091 Rocky Eo
* DRMDB를 생성하고, User, Game, GameUser 테이블을 생성한다.
*/
DROP DATABASE IF EXISTS DRMDB;
CREATE DATABASE DRMDB;
COMMIT;


use DRMDB;

CREATE TABLE Users (
    Uno INTEGER PRIMARY KEY,
    UName VARCHAR(40)
);

CREATE TABLE Game (
    Gno INTEGER PRIMARY KEY,
    GName VARCHAR(60)
);

CREATE TABLE Orders (
    UNo INTEGER,
    GNo INTEGER,
    ONo INTEGER,
    FOREIGN KEY (UNo) REFERENCES Users(UNo),
    FOREIGN KEY (GNo) REFERENCES Game(GNo),
    PRIMARY KEY (UNo, GNo)
);

CREATE TABLE DRM(
    ONo INTEGER,
    DRMNo VARCHAR(20),
    PRIMARY KEY (ONo)
);